/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Main;
import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
public class CambioProductores extends javax.swing.JFrame {
    private NewJFrame newJFrame = NewJFrame.getInstance();
    /**
     * Creates new form CambioProductores
     */
    public CambioProductores() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        empleado1.setText("");
        empleado2.setText("");
        empleado3.setText("");
        empleado4.setText("");
        empleado5.setText("");
        empleado6.setText("");
        empleado7.setText("");
        empleado8.setText("");
        empleado9.setText("");
        
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CantidadIntroInterfaz = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        empleado1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        CantidadProductoresIntro = new javax.swing.JLabel();
        CantidadProductoresInicio = new javax.swing.JLabel();
        CantidadProductoresCreditos = new javax.swing.JLabel();
        CantidadProductoresPlot = new javax.swing.JLabel();
        CantidadProductoresCierre = new javax.swing.JLabel();
        empleado2 = new javax.swing.JTextField();
        empleado3 = new javax.swing.JTextField();
        empleado = new javax.swing.JTextField();
        empleado5 = new javax.swing.JTextField();
        empleado4 = new javax.swing.JTextField();
        empleado6 = new javax.swing.JTextField();
        empleado7 = new javax.swing.JTextField();
        empleado8 = new javax.swing.JTextField();
        empleado9 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        RolEmpleado1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        RolEmpleado2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cambiar Empleados Rick y Morty");

        jLabel2.setText("Empleado 1");

        jLabel3.setText("Empleado 2");

        jLabel4.setText("Empleado 3");

        jLabel5.setText("Empleado 4");

        jLabel6.setText("Empleado 5");

        jLabel7.setText("Empleado 6");

        jLabel8.setText("Empleado 7");

        jLabel9.setText("Empleado 8");

        jLabel10.setText("Empleado 9");

        jLabel11.setText("Empleado 10");

        jButton1.setText("VOLVER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        empleado1.setText("   ");
        empleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Indique opcion");

        jLabel13.setText("1. Intro.");

        jLabel14.setText("2. Creditos. ");

        jLabel15.setText("3. Inicio.");

        jLabel16.setText("4. Cierre.");

        jLabel17.setText("5. Plot.");

        jLabel19.setText("Cantidad de Productores Intro");

        jLabel20.setText("Cantidad de Productores Inicios");

        jLabel21.setText("Cantidad de Productores Creditos");

        jLabel22.setText("Cantidad de Productores Plot ");

        jLabel23.setText("Cantidad de Productores de Cierre");

        CantidadProductoresIntro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CantidadProductoresIntro.setText("2");

        CantidadProductoresInicio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CantidadProductoresInicio.setText("3");

        CantidadProductoresCreditos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CantidadProductoresCreditos.setText("1");

        CantidadProductoresPlot.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CantidadProductoresPlot.setText("1");

        CantidadProductoresCierre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CantidadProductoresCierre.setText("2");

        empleado2.setText("   ");
        empleado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado2ActionPerformed(evt);
            }
        });

        empleado3.setText("   ");
        empleado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado3ActionPerformed(evt);
            }
        });

        empleado.setText("   ");
        empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoActionPerformed(evt);
            }
        });

        empleado5.setText("   ");
        empleado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado5ActionPerformed(evt);
            }
        });

        empleado4.setText("   ");
        empleado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado4ActionPerformed(evt);
            }
        });

        empleado6.setText("   ");
        empleado6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado6ActionPerformed(evt);
            }
        });

        empleado7.setText("   ");
        empleado7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado7ActionPerformed(evt);
            }
        });

        empleado8.setText("   ");
        empleado8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado8ActionPerformed(evt);
            }
        });

        empleado9.setText("   ");
        empleado9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado9ActionPerformed(evt);
            }
        });

        jButton3.setText("Enviar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Enviar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Envar");

        jButton6.setText("Enviar");

        RolEmpleado1.setText("Intro");

        jLabel18.setText("Area");

        RolEmpleado2.setText("Intro");

        jLabel24.setText("Cantidad de emsambladores");

        jLabel25.setText("1");

        javax.swing.GroupLayout CantidadIntroInterfazLayout = new javax.swing.GroupLayout(CantidadIntroInterfaz);
        CantidadIntroInterfaz.setLayout(CantidadIntroInterfazLayout);
        CantidadIntroInterfazLayout.setHorizontalGroup(
            CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                        .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                .addGap(412, 412, 412)
                                .addComponent(jLabel1))
                            .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel19))
                                .addGap(84, 84, 84)
                                .addComponent(CantidadProductoresCierre)))
                        .addGap(461, 461, 461))
                    .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel18)
                        .addGap(27, 27, 27)
                        .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addGap(41, 41, 41))
                            .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RolEmpleado1)
                                            .addComponent(jLabel2)))
                                    .addComponent(jLabel17)
                                    .addComponent(empleado1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                        .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(empleado2)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(27, 27, 27)
                                                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(empleado3)))
                                            .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                                .addComponent(jButton3)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton4)))
                                        .addGap(33, 33, 33)
                                        .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(empleado5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                        .addComponent(RolEmpleado2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(empleado4))
                                .addGap(88, 88, 88)
                                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel8))
                                    .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(empleado6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45)
                                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel10))
                                    .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                        .addComponent(empleado7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(empleado9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CantidadIntroInterfazLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CantidadProductoresPlot)
                            .addComponent(CantidadProductoresInicio)
                            .addComponent(CantidadProductoresIntro)
                            .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                                .addComponent(CantidadProductoresCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addComponent(jLabel24)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel25)))
                        .addGap(343, 343, 343)))
                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empleado8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel11))
                .addContainerGap())
        );
        CantidadIntroInterfazLayout.setVerticalGroup(
            CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RolEmpleado1)
                    .addComponent(jLabel18)
                    .addComponent(RolEmpleado2))
                .addGap(18, 18, 18)
                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(37, 37, 37)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(42, 42, 42)
                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleado5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleado6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleado7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleado8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleado9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(CantidadProductoresIntro))
                .addGap(18, 18, 18)
                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(CantidadProductoresInicio))
                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CantidadProductoresCreditos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)))
                    .addGroup(CantidadIntroInterfazLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))))
                .addGap(18, 18, 18)
                .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CantidadIntroInterfazLayout.createSequentialGroup()
                        .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(CantidadProductoresPlot))
                        .addGap(18, 18, 18)
                        .addGroup(CantidadIntroInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(CantidadProductoresCierre))))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CantidadIntroInterfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CantidadIntroInterfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        newJFrame.setVisible(true);
        newJFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String ProductorIntro = "Intro";
        String ProductorInicio = "Inicio";
        String ProductorCreditos = "Creditos";
        String ProductorCierre = "Cierre";
        String ProductorPlot = "Plot";
        
            try{
            String answer = empleado1.getText();
            int option = Integer.parseInt(answer);
            if (option == 1){
                
                Main.hiloRym1.CambiarTipo(ProductorIntro);
                
                   CantidadProductoresIntro.setText(Integer.toString(Main.CantidadProductoresIntro));
                   CantidadProductoresInicio.setText(Integer.toString(Main.CantidadProductoresInicio));
                   CantidadProductoresCreditos.setText(Integer.toString(Main.CantidadProductoresCreditos));
                   CantidadProductoresCierre.setText(Integer.toString(Main.CantidadProductoresCierre));
                   CantidadProductoresPlot.setText(Integer.toString(Main.CantidadProductoresplot));
                
            }
            else if (option == 2 ){
                
                Main.hiloRym1.CambiarTipo(ProductorCreditos);
                
                   CantidadProductoresIntro.setText(Integer.toString(Main.CantidadProductoresIntro));
                   CantidadProductoresInicio.setText(Integer.toString(Main.CantidadProductoresInicio));
                   CantidadProductoresCreditos.setText(Integer.toString(Main.CantidadProductoresCreditos));
                   CantidadProductoresCierre.setText(Integer.toString(Main.CantidadProductoresCierre));
                   CantidadProductoresPlot.setText(Integer.toString(Main.CantidadProductoresplot));
            }
            else if (option ==3 ){
                Main.hiloRym1.CambiarTipo(ProductorInicio);
                   CantidadProductoresIntro.setText(Integer.toString(Main.CantidadProductoresIntro));
                   CantidadProductoresInicio.setText(Integer.toString(Main.CantidadProductoresInicio));
                   CantidadProductoresCreditos.setText(Integer.toString(Main.CantidadProductoresCreditos));
                   CantidadProductoresCierre.setText(Integer.toString(Main.CantidadProductoresCierre));
                   CantidadProductoresPlot.setText(Integer.toString(Main.CantidadProductoresplot));
            }
            else if (option ==4 ){
                Main.hiloRym1.CambiarTipo(ProductorCierre);
                   CantidadProductoresIntro.setText(Integer.toString(Main.CantidadProductoresIntro));
                   CantidadProductoresInicio.setText(Integer.toString(Main.CantidadProductoresInicio));
                   CantidadProductoresCreditos.setText(Integer.toString(Main.CantidadProductoresCreditos));
                   CantidadProductoresCierre.setText(Integer.toString(Main.CantidadProductoresCierre));
                   CantidadProductoresPlot.setText(Integer.toString(Main.CantidadProductoresplot));
            }
            else if (option == 5 ){
                Main.hiloRym1.CambiarTipo(ProductorPlot);
                   CantidadProductoresIntro.setText(Integer.toString(Main.CantidadProductoresIntro));
                   CantidadProductoresInicio.setText(Integer.toString(Main.CantidadProductoresInicio));
                   CantidadProductoresCreditos.setText(Integer.toString(Main.CantidadProductoresCreditos));
                   CantidadProductoresCierre.setText(Integer.toString(Main.CantidadProductoresCierre));
                   CantidadProductoresPlot.setText(Integer.toString(Main.CantidadProductoresplot));
            } else {
                throw new Exception ("No valido");
            }
            
            RolEmpleado1.setText(Main.hiloRym1.VerTipo());
            
             }catch (Exception e){
                JOptionPane.showMessageDialog(null,"No es una opcion valida");
                empleado1.setText("");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void empleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleado1ActionPerformed

    private void empleado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleado2ActionPerformed

    private void empleado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleado3ActionPerformed

    private void empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleadoActionPerformed

    private void empleado5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleado5ActionPerformed

    private void empleado4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleado4ActionPerformed

    private void empleado6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleado6ActionPerformed

    private void empleado7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleado7ActionPerformed

    private void empleado8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleado8ActionPerformed

    private void empleado9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleado9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String ProductorIntro = "Intro";
        String ProductorInicio = "Inicio";
        String ProductorCreditos = "Creditos";
        String ProductorCierre = "Cierre";
        String ProductorPlot = "Plot";
        
            try{
            String answer = empleado2.getText();
            int option = Integer.parseInt(answer);
            if (option == 1){
                
                Main.hiloRym2.CambiarTipo(ProductorIntro);
                
                   CantidadProductoresIntro.setText(Integer.toString(Main.CantidadProductoresIntro));
                   CantidadProductoresInicio.setText(Integer.toString(Main.CantidadProductoresInicio));
                   CantidadProductoresCreditos.setText(Integer.toString(Main.CantidadProductoresCreditos));
                   CantidadProductoresCierre.setText(Integer.toString(Main.CantidadProductoresCierre));
                   CantidadProductoresPlot.setText(Integer.toString(Main.CantidadProductoresplot));
                
            }
            else if (option == 2 ){
                
                Main.hiloRym2.CambiarTipo(ProductorCreditos);
                
                   CantidadProductoresIntro.setText(Integer.toString(Main.CantidadProductoresIntro));
                   CantidadProductoresInicio.setText(Integer.toString(Main.CantidadProductoresInicio));
                   CantidadProductoresCreditos.setText(Integer.toString(Main.CantidadProductoresCreditos));
                   CantidadProductoresCierre.setText(Integer.toString(Main.CantidadProductoresCierre));
                   CantidadProductoresPlot.setText(Integer.toString(Main.CantidadProductoresplot));
            }
            else if (option ==3 ){
                Main.hiloRym2.CambiarTipo(ProductorInicio);
                   CantidadProductoresIntro.setText(Integer.toString(Main.CantidadProductoresIntro));
                   CantidadProductoresInicio.setText(Integer.toString(Main.CantidadProductoresInicio));
                   CantidadProductoresCreditos.setText(Integer.toString(Main.CantidadProductoresCreditos));
                   CantidadProductoresCierre.setText(Integer.toString(Main.CantidadProductoresCierre));
                   CantidadProductoresPlot.setText(Integer.toString(Main.CantidadProductoresplot));
            }
            else if (option ==4 ){
                Main.hiloRym2.CambiarTipo(ProductorCierre);
                   CantidadProductoresIntro.setText(Integer.toString(Main.CantidadProductoresIntro));
                   CantidadProductoresInicio.setText(Integer.toString(Main.CantidadProductoresInicio));
                   CantidadProductoresCreditos.setText(Integer.toString(Main.CantidadProductoresCreditos));
                   CantidadProductoresCierre.setText(Integer.toString(Main.CantidadProductoresCierre));
                   CantidadProductoresPlot.setText(Integer.toString(Main.CantidadProductoresplot));
            }
            else if (option == 5 ){
                Main.hiloRym2.CambiarTipo(ProductorPlot);
                   CantidadProductoresIntro.setText(Integer.toString(Main.CantidadProductoresIntro));
                   CantidadProductoresInicio.setText(Integer.toString(Main.CantidadProductoresInicio));
                   CantidadProductoresCreditos.setText(Integer.toString(Main.CantidadProductoresCreditos));
                   CantidadProductoresCierre.setText(Integer.toString(Main.CantidadProductoresCierre));
                   CantidadProductoresPlot.setText(Integer.toString(Main.CantidadProductoresplot));
            } else {
                throw new Exception ("No valido");
            }
            
            RolEmpleado2.setText(Main.hiloRym2.VerTipo());
            
             }catch (Exception e){
                JOptionPane.showMessageDialog(null,"No es una opcion valida");
                empleado1.setText("");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioProductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioProductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioProductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioProductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioProductores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CantidadIntroInterfaz;
    private javax.swing.JLabel CantidadProductoresCierre;
    private javax.swing.JLabel CantidadProductoresCreditos;
    private javax.swing.JLabel CantidadProductoresInicio;
    private javax.swing.JLabel CantidadProductoresIntro;
    private javax.swing.JLabel CantidadProductoresPlot;
    private javax.swing.JLabel RolEmpleado1;
    private javax.swing.JLabel RolEmpleado2;
    private javax.swing.JTextField empleado;
    private javax.swing.JTextField empleado1;
    private javax.swing.JTextField empleado2;
    private javax.swing.JTextField empleado3;
    private javax.swing.JTextField empleado4;
    private javax.swing.JTextField empleado5;
    private javax.swing.JTextField empleado6;
    private javax.swing.JTextField empleado7;
    private javax.swing.JTextField empleado8;
    private javax.swing.JTextField empleado9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
